"""добавили колонку описание и убрали жанр у игр

Revision ID: a9b834e7ec8e
Revises: 9cc318947f13
Create Date: 2023-04-23 10:54:41.319892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b834e7ec8e'
down_revision = '9cc318947f13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
